### ISSUE TITLE
日志挖掘无法选择日志文件

### ISSUE THREAD

**Issue by kejincan** [gumengkai/dbmon#2]
![image](https://user-images.githubusercontent.com/40883481/49203575-cc914b80-f3e3-11e8-97d1-2724dd87e2ea.png)

**Comment by gumengkai** [comment]
日志挖掘已完善，目前基本可用
![image](https://user-images.githubusercontent.com/22426858/49411553-476fb300-f7a4-11e8-93c8-e6e6a25132a5.png)
